fixed repo url to be https so it works
i was having error (below) fixed it by adding an s http(s)

root@carter:/campaigns# sh gitflow-installer.sh 
### gitflow no-make installer ###
Installing git-flow to /usr/local/bin
Cloning repo from GitHub to gitflow
Initialized empty Git repository in /campaigns/gitflow/.git/
error: RPC failed; result=22, HTTP code = 405